// <auto-generated />
using System;
using MarketData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarketData.Data.Migrations
{
    [DbContext(typeof(MarketDataDbContext))]
    partial class MarketDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarketData.Data.Models.AppraisedValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("antiguedad_vivienda");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<decimal>("PricePerSquareMeter")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_m2");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_provincia");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceCode", "Period", "Age")
                        .IsUnique();

                    b.ToTable("valores_tasados", null, t =>
                        {
                            t.HasCheckConstraint("ck_valores_tasados_antiguedad", "antiguedad_vivienda IN ('<=5', '>5')");
                        });
                });

            modelBuilder.Entity("MarketData.Data.Models.CacheEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave_cache");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contenido");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique();

                    b.ToTable("datos_cache", (string)null);
                });

            modelBuilder.Entity("MarketData.Data.Models.HousingSale", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HousingStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado_vivienda");

                    b.Property<int>("OperationsCount")
                        .HasColumnType("integer")
                        .HasColumnName("numero_operaciones");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_provincia");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceCode", "Period", "HousingStatus")
                        .IsUnique();

                    b.ToTable("compraventas_vivienda", null, t =>
                        {
                            t.HasCheckConstraint("ck_compraventas_estado_vivienda", "estado_vivienda IN ('nueva', 'segunda_mano')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
