// <auto-generated />
using System;
using Analytics.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Analytics.Migrations
{
    [DbContext(typeof(AnalyticsDbContext))]
    [Migration("20260926101003_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Analytics.Models.PropertyScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("ActivityIndex")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("indice_actividad");

                    b.Property<decimal>("ActivityIndexNationalRanking")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("indice_actividad_ranking_nacional");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_calculo");

                    b.Property<DateOnly>("Period")
                        .HasColumnType("date")
                        .HasColumnName("periodo");

                    b.Property<decimal>("PriceIndex")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("indice_precio");

                    b.Property<decimal>("PriceIndexNationalRanking")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("indice_precio_ranking_nacional");

                    b.Property<decimal?>("PriceTrendIndex")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("indice_tendencia_precio");

                    b.Property<decimal?>("PriceTrendIndexYearOverYear")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("indice_tendencia_precio_interanual");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_provincia");

                    b.Property<decimal?>("Score")
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("property_score");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceCode", "Period")
                        .IsUnique();

                    b.ToTable("property_scores", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
