// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Property.Data;

#nullable disable

namespace Property.Migrations
{
    [DbContext(typeof(PropertyDbContext))]
    [Migration("20260912173133_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Property.Models.Favorite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("ProvinceCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_provincia");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceCode");

                    b.HasIndex("UserId", "ProvinceCode")
                        .IsUnique();

                    b.ToTable("favoritos", (string)null);
                });

            modelBuilder.Entity("Property.Models.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AutonomousCommunity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comunidad_autonoma");

                    b.Property<string>("CodeIne")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("codigo_ine");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("Population")
                        .HasColumnType("integer")
                        .HasColumnName("poblacion");

                    b.HasKey("Id");

                    b.HasIndex("CodeIne")
                        .IsUnique();

                    b.ToTable("provincias", (string)null);
                });

            modelBuilder.Entity("Property.Models.Favorite", b =>
                {
                    b.HasOne("Property.Models.Province", null)
                        .WithMany()
                        .HasForeignKey("ProvinceCode")
                        .HasPrincipalKey("CodeIne")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
